//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelSheetNameList.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelSheetNameList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG000 {
            get {
                return ResourceManager.GetString("ERRMSG000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したファイルは使用中です。閉じてから再選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG001 {
            get {
                return ResourceManager.GetString("ERRMSG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1ファイルのみドラッグ&amp;ドロップ可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG002 {
            get {
                return ResourceManager.GetString("ERRMSG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したファイルはExcelファイルではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG003 {
            get {
                return ResourceManager.GetString("ERRMSG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xls形式に対応していません。xlsx形式に変換してからご利用ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG004 {
            get {
                return ResourceManager.GetString("ERRMSG004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEADER_COL000 {
            get {
                return ResourceManager.GetString("HEADER_COL000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEADER_COL001 {
            get {
                return ResourceManager.GetString("HEADER_COL001", resourceCulture);
            }
        }
    }
}
